ALTER TABLE "application_schema_version" DROP CONSTRAINT "application_schema_version_current";--> statement-breakpoint
ALTER TABLE "coherence_checkpoints" DROP CONSTRAINT "coherence_checkpoints_safety_reason";--> statement-breakpoint
ALTER TABLE "draft_operation_states" DROP CONSTRAINT "draft_operation_states_safety_reason";--> statement-breakpoint
ALTER TABLE "review_operation_states" DROP CONSTRAINT "review_operation_states_safety_reason";--> statement-breakpoint
ALTER TABLE "revision_operation_states" DROP CONSTRAINT "revision_operation_states_safety_reason";--> statement-breakpoint
UPDATE "application_schema_version" SET "version"=56,"applied_at"=clock_timestamp() WHERE "singleton"=true;--> statement-breakpoint
ALTER TABLE "application_schema_version" ADD CONSTRAINT "application_schema_version_current" CHECK ("application_schema_version"."version"=56);--> statement-breakpoint
ALTER TABLE "coherence_checkpoints" ADD CONSTRAINT "coherence_checkpoints_safety_reason" CHECK ((("coherence_checkpoints"."status"='started' and "coherence_checkpoints"."ambiguity_reason" is null) or ("coherence_checkpoints"."status"='provider_in_flight' and "coherence_checkpoints"."release_reason" is null and "coherence_checkpoints"."ambiguity_reason" is not null and "coherence_checkpoints"."ambiguity_reason" in ('provider_in_flight_without_checkpoint','external_side_effect_without_checkpoint','legacy_dispatch_outcome_unknown')) or ("coherence_checkpoints"."status"='checkpointed' and "coherence_checkpoints"."release_reason" is null and "coherence_checkpoints"."ambiguity_reason" is null)) and ("coherence_checkpoints"."release_reason" is null or ("coherence_checkpoints"."status"='started' and "coherence_checkpoints"."release_reason" in ('configuration_before_dispatch','authentication_before_dispatch','billing_before_dispatch','validation_before_dispatch'))));--> statement-breakpoint
ALTER TABLE "draft_operation_states" ADD CONSTRAINT "draft_operation_states_safety_reason" CHECK ((("draft_operation_states"."status"='started' and "draft_operation_states"."ambiguity_reason" is null) or ("draft_operation_states"."status"='provider_in_flight' and "draft_operation_states"."release_reason" is null and "draft_operation_states"."ambiguity_reason" is not null and "draft_operation_states"."ambiguity_reason" in ('provider_in_flight_without_checkpoint','external_side_effect_without_checkpoint','legacy_dispatch_outcome_unknown')) or ("draft_operation_states"."status"='checkpointed' and "draft_operation_states"."release_reason" is null and "draft_operation_states"."ambiguity_reason" is null)) and ("draft_operation_states"."release_reason" is null or ("draft_operation_states"."status"='started' and "draft_operation_states"."release_reason" in ('configuration_before_dispatch','authentication_before_dispatch','billing_before_dispatch','validation_before_dispatch'))));--> statement-breakpoint
ALTER TABLE "review_operation_states" ADD CONSTRAINT "review_operation_states_safety_reason" CHECK ((("review_operation_states"."status"='started' and "review_operation_states"."ambiguity_reason" is null) or ("review_operation_states"."status"='provider_in_flight' and "review_operation_states"."release_reason" is null and "review_operation_states"."ambiguity_reason" is not null and "review_operation_states"."ambiguity_reason" in ('provider_in_flight_without_checkpoint','external_side_effect_without_checkpoint','legacy_dispatch_outcome_unknown')) or ("review_operation_states"."status"='checkpointed' and "review_operation_states"."release_reason" is null and "review_operation_states"."ambiguity_reason" is null)) and ("review_operation_states"."release_reason" is null or ("review_operation_states"."status"='started' and "review_operation_states"."release_reason" in ('configuration_before_dispatch','authentication_before_dispatch','billing_before_dispatch','validation_before_dispatch'))));--> statement-breakpoint
ALTER TABLE "revision_operation_states" ADD CONSTRAINT "revision_operation_states_safety_reason" CHECK ((("revision_operation_states"."status"='started' and "revision_operation_states"."ambiguity_reason" is null) or ("revision_operation_states"."status"='provider_in_flight' and "revision_operation_states"."release_reason" is null and "revision_operation_states"."ambiguity_reason" is not null and "revision_operation_states"."ambiguity_reason" in ('provider_in_flight_without_checkpoint','external_side_effect_without_checkpoint','legacy_dispatch_outcome_unknown')) or ("revision_operation_states"."status"='checkpointed' and "revision_operation_states"."release_reason" is null and "revision_operation_states"."ambiguity_reason" is null)) and ("revision_operation_states"."release_reason" is null or ("revision_operation_states"."status"='started' and "revision_operation_states"."release_reason" in ('configuration_before_dispatch','authentication_before_dispatch','billing_before_dispatch','validation_before_dispatch'))));